/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 turnik.gltf 
Author: BenchK (https://sketchfab.com/benchk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/benchk-black-dip-bar-and-pull-up-bar-2in1-d8-2-cc8aab29c0954bc6ba48eda399328939
Title: BENCHK: BLACK DIP BAR AND PULL-UP BAR 2IN1 D8 2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/turnik.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.585, 0.274, 0.469]}>
          <group position={[-0.585, -0.274, -0.469]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.PEN_MATERIAL89} />
            <mesh geometry={nodes.Object_5.geometry} material={materials['Farba_-_Ciemnosz']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/turnik.gltf')
