/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 xia.gltf 
Author: Silversea-Media-SG (https://sketchfab.com/SilverSeaMediaSG)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/xiaomi-smart-tv-55-7a297e9bbb784fe5bf2859745dc0bc3b
Title: Xiaomi - Smart TV 55"
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/xia.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, -4.041, 44.226]}>
            <mesh geometry={nodes.screen_screen_0.geometry} material={materials.screen} />
            <mesh geometry={nodes.screen_body_0.geometry} material={materials.body} />
            <mesh geometry={nodes.screen_stand_0.geometry} material={materials.stand} />
            <mesh geometry={nodes.screen_body_0_1.geometry} material={materials.body_0} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/xia.gltf')
